// ERROR TYPES FOR DATABASE STORAGE
export const ERROR_TYPE = {
  GENERAL: "GENERAL",
  INVALID_REQUEST: "INVALID_REQUEST",
  SCRAPER_FAILED: "SCRAPER_FAILED",
  UNSUPPORTED_WEBSITE_REQ: "UNSUPPORTED_WEBSITE_REQ",
  TRACKER_NOT_DELETED: "TRACKER_NOT_DELETED",
  MESSAGE_NOT_SENT: "MESSAGE_NOT_SENT",
};
