export const ERROR_TYPE = {
  BOTH_SCRAPER_FAILED: "BOTH_SCRAPER_FAILED",
  UNSUPPORTED_WEBSITE_REQ: "UNSUPPORTED_WEBSITE_REQ",
  TRACKER_NOT_DELETED: "TRACKER_NOT_DELETED",
  MESSAGE_NOT_SENT: "MESSAGE_NOT_SENT",
};
